### PR TITLE
fix(web): Conversation comments should appear differently than messages

### LINKED ISSUE #355: fix(web): Display Comments Differently
if its a comment, then use a lighter shade of blue with black text

### PR DESCRIPTION
**Pull request by Flo4604**
## What does this PR do?
:black_heart: 

This Fixes #355, comments should be able to be differentiated from Norma Emails. 
They are now displayed in a light / more dark blue color and black text which is not close to the actual conversation.

_If there is not an issue for this, please create one first. This is used to tracking purposes and also helps use understand why this PR exists_

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Required

- [X] Read [Contributing Guide](https://github.com/un/inbox/blob/main/CONTRIBUTING.md)
- [X] Self-reviewed my own code
- [X] Tested my code in a local environment
- [X] Commented on my code in hard-to-understand areas
- [X] Checked for warnings, there are none
- [X] Removed all `console.logs`
- [X] Merged the latest changes from main onto my branch with `git pull origin main`
- [X] My changes don't cause any responsiveness issues

### Appreciated

- [X] If a UI change was made: Added a screen recording or screenshots to this PR
- [X] Updated the UnInbox Docs if changes were necessary

### CODE REVIEW

File: apps/web-app/components/convos/convoMessageItem.vue [hunk 1]
```diff
@@ -57,14 +57,11 @@
   });
 
   const typeClasses = computed(() => {
-    if (userIsAuthor.value) {
-      return 'bg-blue-10 text-white';
-    }
```
Comment (McPizza0) [inline apps/web-app/components/convos/convoMessageItem.vue:62]: we need to keep this to mark the user's own messages in blue
i would suggest copying the below `switch / case` block here to only change the styling if the current user is the author of the message

File: apps/web-app/components/convos/convoMessageItem.vue [hunk 2]
```diff
@@ -57,14 +57,11 @@
...
     switch (messageType.value) {
       case 'message':
-        return 'bg-base-5 text-base-12';
+        return 'bg-blue-10 text-white bg-base-5 text-base-12';
       case 'comment':
-        return 'bg-base-4 text-base-12 ';
+        return 'bg-blue-5 text-black bg-base-4 text-base-12 ';
```
Comment (McPizza0) [inline apps/web-app/components/convos/convoMessageItem.vue:64]: once we've copied the switch case block to the `if (userIsAuthor.value)` check, we would need to revert these

**Review by McPizza0 — CHANGES_REQUESTED** [review]

**Comment by Flo4604** [comment]
Made requested changes, 



Now looks like this.

**Review by McPizza0 — APPROVED** [review]
