### PR TITLE
feat(web,platfrom): Onboarding UI updates and redirect loop fix

### LINKED ISSUE #292: 2fa input
when selecting a digit on 2fa input can get this error
https://discord.com/channels/1113119653246545961/1227194242020020254/1227194242020020254

### LINKED ISSUE #294: web: mobile help menu renders offscreen
need to move popout position on mobile devices to left instead of right

### PR DESCRIPTION
**Pull request by BlankParticle**
## What does this PR do?

Fixes #294
Fixes #292

Also extra fixes in backend for redirect loop.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Required

- [ ] Read [Contributing Guide](https://github.com/un/inbox/blob/main/CONTRIBUTING.md)
- [ ] Self-reviewed my own code
- [ ] Tested my code in a local environment
- [ ] Commented on my code in hard-to-understand areas
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the UnInbox Docs if changes were necessary

### CODE REVIEW

**Comment by BlankParticle** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/un/inbox/295?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#295** <a href="https://app.graphite.dev/github/pr/un/inbox/295?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#291** <a href="https://app.graphite.dev/github/pr/un/inbox/291?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @BlankParticle and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

File: apps/web-app/pages/redirect.vue [hunk 1]
```diff
@@ -1,12 +1,20 @@
...
+    const usernameCookie = useCookie('un-join-username', {
+      maxAge: 3600
+    });
+
+    if (process.client && !usernameCookie.value && username) {
+      usernameCookie.value = username;
+    }
+
     if (!twoFactorEnabledCorrectly) {
       return navigateTo(`/join/2fa`);
```
Comment (McPizza0) [inline apps/web-app/pages/redirect.vue:19]: this may be a problem if they already have an org set up
we should set a cookie or something so the join/2fa page will redirect back to org when done

Comment (BlankParticle) [reply apps/web-app/pages/redirect.vue:19]: check if the user have org already, if they have a org skip it.

Comment (McPizza0) [reply apps/web-app/pages/redirect.vue:19]: maybe, but then they wont set up 2fa again

Comment (BlankParticle) [reply apps/web-app/pages/redirect.vue:19]: ah, do you have a better plan?

**Review by McPizza0 — APPROVED** [review]
