### PR TITLE
fix: logs for duplicate invite

### LINKED ISSUE #750: (bug): duplicate email in invite shows error logs.
### Step to produce:

1. Add an invite to user with some email
2. Add another invite to another from same email

Capture

### PR DESCRIPTION
**Pull request by SySagar**
## What does this PR do?

Fixes #750 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Required

- [x] Read [Contributing Guide](https://github.com/un/inbox/blob/main/CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Tested my code in a local environment
- [x] Commented on my code in hard-to-understand areas
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### CODE REVIEW

**Comment by McPizza0** [comment]
@SySagar Great work
the checks are failing
can you check them locally with `pnpm run check`

**Comment by SySagar** [comment]
@McPizza0 please check.

File: apps/platform/trpc/routers/orgRouter/users/invitesRouter.ts [hunk 1]
```diff
@@ -227,17 +245,25 @@ export const invitesRouter = router({
...
+            orgId: orgId,
+            invitedByOrgMemberId: orgMemberId,
+            orgMemberId: +newOrgMemberResponse.insertId,
+            role: newOrgMember.role,
+            email: notification?.notificationEmailAddress ?? null,
+            inviteToken: newInviteToken,
+            invitedOrgMemberProfileId: orgMemberProfileId,
+            expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000) // 7 Days from now
+          })
+          .catch((err) => {
```
Comment (BlankParticle) [inline apps/platform/trpc/routers/orgRouter/users/invitesRouter.ts:261]: You don't need catch here, trpc handles that part if you are gonna throw error anyways. It's actually better to throw the Original error as it helps in debugging

File: apps/web/src/app/[orgShortcode]/settings/org/users/invites/_components/invite-modal.tsx [hunk 2]
```diff
@@ -83,6 +83,9 @@ export function InviteModal() {
       form.reset();
       void invalidateInvites.invalidate();
       setOpen(false);
+    },
+    onError: (error) => {
```
Comment (BlankParticle) [inline apps/web/src/app/[orgShortcode]/settings/org/users/invites/_components/invite-modal.tsx:87]: don't set a `onError` callback unless you need to do any specific work, if you catch the error here it would not go to the global handler which would render out the error toast

**Review by BlankParticle — CHANGES_REQUESTED** [review]
don't handle error if you are going to rethrow them without using the error for anything else

File: apps/web/src/app/[orgShortcode]/settings/org/users/invites/_components/invite-modal.tsx (hunk 2 above)
Comment (SySagar) [reply apps/web/src/app/[orgShortcode]/settings/org/users/invites/_components/invite-modal.tsx:87]: ok sol how would you want me to handle this?

Comment (SySagar) [reply apps/web/src/app/[orgShortcode]/settings/org/users/invites/_components/invite-modal.tsx:87]: Capture


Would it be ok if I simply remove the error part inside the modal. or we will go with the above approch?

Comment (BlankParticle) [reply apps/web/src/app/[orgShortcode]/settings/org/users/invites/_components/invite-modal.tsx:87]: ah it is being handled in a modal, you can just do this

```ts
onError: () => void 0,
````

File: apps/platform/trpc/routers/orgRouter/users/invitesRouter.ts (hunk 1 above)
Comment (SySagar) [reply apps/platform/trpc/routers/orgRouter/users/invitesRouter.ts]: fixed.

File: apps/web/src/app/[orgShortcode]/settings/org/users/invites/_components/invite-modal.tsx (hunk 2 above)
Comment (SySagar) [reply apps/web/src/app/[orgShortcode]/settings/org/users/invites/_components/invite-modal.tsx]: Yup works! Have updated it.

**Review by BlankParticle — APPROVED** [review]

**Comment by McPizza0** [comment]
### Merge activity

* **Aug 31, 3:32 AM EDT**: [Graphite](https://app.graphite.dev/github/pr/un/inbox/758) couldn't merge this PR because it failed for an unknown reason (Stack merges are not currently supported for forked repositories. Please create a branch in the target repository in order to merge).
